# -*- coding: utf-8 -*-
"""Flask.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Y93TWC1-dQ223iPCKAuEWLPuny238Odv
"""

import numpy as np 
import pandas as pd
import sklearn

df = pd.read_csv("hiring.csv")
df

df['test_score'].fillna(df['test_score'].mean(), inplace=True)
df

df['experience'].fillna(0, inplace=True)
df

def word(word):
  dict = {"five": 5, "two": 2, "seven": 7, "three": 3, "ten": 10, "eleven": 11, 0:0}
  return dict[word]

df['experience'] = df['experience'].apply(lambda x: word(x))
df

x = df.drop(columns=['salary'], axis= 'columns')
y = df['salary']

from sklearn.model_selection import train_test_split
xtrain, xtest, ytrain, ytest = train_test_split(x, y, test_size=0.3, random_state=5)

from sklearn.linear_model import LinearRegression
lr = LinearRegression()
mymodel = lr.fit(xtrain, ytrain)
mymodel

ypred = mymodel.predict(xtest)
pd.DataFrame({"Actual": ytest, "Predict": ypred})

from sklearn.externals import joblib
joblib.dump(mymodel, 'model_j')
model = joblib.load('model_j')

model.predict(xtest)

